/**
 * Created by jim on 2017/6/23.
 */
import {
    TASK_LIST_SUBSCRIPTION,
    TASK_INSERT_METHOD,
    TASK_LIST_METHOD,
} from './constant';
import {STOP_SUBSCRIPTION} from 'meteor-redux-middlewares';

const TASK_LIST_SUBSCRIPTION_READY = 'TASK_LIST_SUBSCRIPTION_READY';
const TASK_LIST_SUBSCRIPTION_CHANGED = 'TASK_LIST_SUBSCRIPTION_CHANGED';

export {
    TASK_LIST_SUBSCRIPTION_READY,
    TASK_LIST_SUBSCRIPTION_CHANGED,
    TASK_LIST_SUBSCRIPTION,
    STOP_SUBSCRIPTION,
    TASK_INSERT_METHOD,
    TASK_LIST_METHOD,
};