/**
 * Created by jim on 2017/6/23.
 */

const CONNECTION_REACTIVE_SOURCE_CHANGED = 'CONNECTION_REACTIVE_SOURCE_CHANGED';
const CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT';

export {
    CONNECTION_REACTIVE_SOURCE_CHANGED,
    CONNECTION_TIMEOUT,
};