/**
 * Created by jim on 2017/6/23.
 */

const STATUS_REACTIVE_SOURCE_CHANGED = 'STATUS_REACTIVE_SOURCE_CHANGED';
const CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT';

export {
    STATUS_REACTIVE_SOURCE_CHANGED,
    CONNECTION_TIMEOUT,
};