/**
 * Created by jim on 2017/6/23.
 */
import {USER_ME_SUBSCRIPTION} from './constant';
import {STOP_SUBSCRIPTION} from 'meteor-redux-middlewares';

const USER_ME_SUBSCRIPTION_READY = 'USER_ME_SUBSCRIPTION_READY';
const USER_ME_SUBSCRIPTION_CHANGED = 'USER_ME_SUBSCRIPTION_CHANGED';

const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGIN = 'USER_LOGIN';
const USER_REGISTER = 'USER_REGISTER';

export {
    USER_ME_SUBSCRIPTION_READY,
    USER_ME_SUBSCRIPTION_CHANGED,
    USER_ME_SUBSCRIPTION,
    STOP_SUBSCRIPTION,
    USER_LOGOUT,
    USER_LOGIN,
    USER_REGISTER,
};