/**
 * Created by jim on 2017/6/23.
 */

const MENU_REACTIVE_SOURCE_CHANGED = 'MENU_REACTIVE_SOURCE_CHANGED';
const ISSUB_REACTIVE_SOURCE_CHANGED = 'ISSUB_REACTIVE_SOURCE_CHANGED';

export {
    MENU_REACTIVE_SOURCE_CHANGED,
    ISSUB_REACTIVE_SOURCE_CHANGED,
};