/**
 * Created by jim on 2017/6/23.
 */
import {
    LIST_PUBLIC_SUBSCRIPTION,
    LIST_PRIVATE_SUBSCRIPTION,
    LIST_PUBLIC_METHOD,
    LIST_PRIVATE_METHOD,
} from './constant';

import {STOP_SUBSCRIPTION} from 'meteor-redux-middlewares';
const LIST_PUBLIC_SUBSCRIPTION_READY = 'LIST_PUBLIC_SUBSCRIPTION_READY';
const LIST_PUBLIC_SUBSCRIPTION_CHANGED = 'LIST_PUBLIC_SUBSCRIPTION_CHANGED';
const LIST_PRIVATE_SUBSCRIPTION_READY = 'LIST_PRIVATE_SUBSCRIPTION_READY';
const LIST_PRIVATE_SUBSCRIPTION_CHANGED = 'LIST_PRIVATE_SUBSCRIPTION_CHANGED';

export {
    LIST_PRIVATE_SUBSCRIPTION_READY,
    LIST_PRIVATE_SUBSCRIPTION_CHANGED,
    LIST_PUBLIC_SUBSCRIPTION_READY,
    LIST_PUBLIC_SUBSCRIPTION_CHANGED,
    STOP_SUBSCRIPTION,
    LIST_PUBLIC_SUBSCRIPTION,
    LIST_PRIVATE_SUBSCRIPTION,
    LIST_PUBLIC_METHOD,
    LIST_PRIVATE_METHOD,
};